### ISSUE TITLE
features extras - massive exchange and pairs support!

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr-site#28]
we don't mention the vast exchange and pairs list. this should have it's own screenshot and "dot" on the website's features section.

**Comment by dllud** [comment]
We do:

> Market data is retrieved directly from the exchanges via Wi-Fi or Mobile Data (if allowed).
> Boilr supports all exchanges available on libdynticker, and all their pairs.

But we can change the text to something like:

> Boilr supports all 70+ exchanges available on libdynticker, and all their pairs. 
> Market data is retrieved directly from the exchanges via Wi-Fi or Mobile Data (if allowed). 

Currently this is on the 9th position. We can change it to the 5th position. What do you think?

**Comment by algazarra** [comment]
"Boilr supports 70+ exchanges and all their pairs."
Along with screen with exchange list showing one of the big alt markets, polo or alike.

+

"

**Comment by dllud** [comment]
You mean apart from the "via Wi-FI..." in a new feature with a screenshot of a pairs list?

**Comment by dllud** [comment]
Thinking it over I am against splitting into 2 different features:
- It's just two short sentences (compare it to the size of the Price Change description).
- The "data is retrieved directly [...]" sentence doesn't seem important enough to have its own separate feature.
- It is difficult to find a good screenshot to go along with "data is retrieved directly [...]".

I say lets just separate them by a paragraph.
