### ISSUE TITLE
Explain permissions

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr-site#29]
Can we have a section with permissions explanation? People don't see why Boilr needs so many.

**Comment by dllud** [comment]
Sure. Where to place it? After "Supported Exchanges"?

BTW, it is all explained on the Google Play listing.

**Comment by algazarra** [comment]
Can we manage to put it on download fork?

**Comment by dllud** [comment]
Neee it would spoil that section and it has nothing to do with it. I prefer a separate section.

**Comment by algazarra** [comment]
OK lets switch download and supported. Supported should be under features. And permissions after download. What do you think?

**Comment by dllud** [comment]
Disagree. Download is way more important than Supported. What you want people to do is to download and try the app. If we could we would put it as the first section. We don't do it because we first need to convince people that Boilr is worth their time by showcasing the features.

**Comment by algazarra** [comment]
Please see #31.

**Comment by dllud** [comment]
#31 Won't get implemented soon. Therefore the order will stay as: Features, Download, Permissions, Supported exchanges, Donate. Seems good?

**Comment by algazarra** [comment]
Yes
