### ISSUE TITLE
Font on windows

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr-site#34]
Font looks bad on windows. Can we change it?

**Comment by andrefbsantos** [comment]
I changed the font to Arial, can you check it?

**Comment by algazarra** [comment]
Only changed in permissions.

**Comment by andrefbsantos** [comment]
https://github.com/twbs/bootstrap/issues/13823
It seems like Helvetica Neue doesn't properly render in random non-Mac OS systems. 

I completely removed Helvetica Neue and it should be better.

**Comment by algazarra** [comment]
Perfect
