### ISSUE TITLE
Support instead of help

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr-site#42]
use support instead of help. NP using it since in the top bar we use exchanges for "supported exchanges" ;)

**Comment by dllud** [comment]
Why? I see *Help* on many website sites and it seems more specific than *Support*.

Just some I was browsing:
https://www.libreoffice.org
http://www.openstreetmap.org

**Comment by algazarra** [comment]
I totally disagree, support is the standard word for that. Take a look at any exchange, they all use support. Since the app is for traders, why diverge from the main players?
