### ISSUE TITLE
"language" top bar

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr-site#44]
instead of "language", can it display current language?

**Comment by dllud** [comment]
Possible but would hinder usability.

**Comment by algazarra** [comment]
you mean if someone uses search to find "language"? I bet most chinese don't know the meaning of "language" =P

**Comment by dllud** [comment]
Nope. I mean you must always state what a config does, that's a basic UX rule. In this case it must be evident that it changes the website language. Showing just a list of options may lead to other interpretations. Check Android, iOS and everywhere else.

Don't bother about a Chinese user not knowing what "language" means. That same user will have his browser in Chinese and thus will enter directly into the Chinese translation.

**Comment by algazarra** [comment]
>user will have his browser in Chinese and thus will enter directly into the Chinese translation.
that's perfect!
